services:
  - type: web
    name: n8n-render
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: N8N_HOST
        value: https://n8n-server-github.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-server-github.onrender.com/
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-server-github.onrender.com/
      - key: N8N_SECURE_COOKIE
        value: true

      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        sync: false
      - key: DB_POSTGRESDB_PORT
        value: 6543
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        sync: false
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: DB_POSTGRESDB_SSL_ENABLED
        value: true

      - key: N8N_ENCRYPTION_KEY
        sync: false

      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: TZ
        value: Asia/Kolkata

      - key: N8N_DIAGNOSTICS_ENABLED
        value: false
      - key: N8N_PERSONALIZATION_ENABLED
        value: false
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: false

      - key: N8N_RUNNERS_ENABLED
        value: true

      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
